# Shell variables
# Generated by 'wal'
wallpaper='/home/mohamed/Pictures/Wallpaper/035.jpg'

# Special
background='#153739'
foreground='#d0c5b8'
cursor='#d0c5b8'

# Colors
color0='#153739'
color1='#738877'
color2='#918E79'
color3='#AC947A'
color4='#E08F6D'
color5='#729481'
color6='#A99D83'
color7='#d0c5b8'
color8='#918980'
color9='#738877'
color10='#918E79'
color11='#AC947A'
color12='#E08F6D'
color13='#729481'
color14='#A99D83'
color15='#d0c5b8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
