--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mohamed/Pictures/Wallpaper/035.jpg"

-- Special
background="#153739"
foreground="#d0c5b8"
cursor="#d0c5b8"

-- Colors
color0="#153739"
color1="#738877"
color2="#918E79"
color3="#AC947A"
color4="#E08F6D"
color5="#729481"
color6="#A99D83"
color7="#d0c5b8"
color8="#918980"
color9="#738877"
color10="#918E79"
color11="#AC947A"
color12="#E08F6D"
color13="#729481"
color14="#A99D83"
color15="#d0c5b8"
